A lot of files are redundant or obsolete. Unfortunately I didn't have time to clean all of them and test the app afterwards. Sorry!

To connect to local database some settings in settings.py must be changed.